### ISSUE TITLE
Can't add liquidity to West/USDN

### ISSUE THREAD

**Issue by travek** [swopfi/swopfi-smart-contracts#12]
I'm trying to add liquidity for WEST/USDN pair.
I got issue: State check failed. Reason: Accounts balance errors.
Before I add liquidity for other pairs and it worked OK.

**Comment by msmolyakov** [comment]
Hi. Please make sure that your account has enough amount of the tokens and enough WAVES to pay transaction fee.

**Comment by travek** [comment]
@msmolyakov 
thanks, I didn't notice I need waves as well for transaction fee. It's OK now.
